server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cathubhome/tensquare-server-config.git
  rabbitmq:
    host: 192.168.17.18

#暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh