server:
  port: ${serverPort:12000}
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: ${configServerGitUri:https://github.com/cathubhome/tensquare-server-config.git}
  rabbitmq:
    host: ${rabbitmqHost:192.168.17.18}
    port: ${rabbitmqPort:5672}
    username: ${rabbitmqUsername:admin}
    password: ${rabbitmqPassword:cathome}

#暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh